site_name: Hazbin Hotel
repo_url: https://github.com/PedroLuisDionisioFraga/poetry-and-pytest-usage
repo_name: PedroLuisDionisioFraga/poetry-and-pytest-usage

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - search
    - content.code.copy
    - content.code.select
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

plugins:
  - macros
  - mkdocstrings:
      handlers:
        python:
          paths: [hazbin_hotel]


extra:
  commands:
  annotate:
    json: [.s2]