on:
  pull_request:
    branches:
      - main

jobs:

  lint:
    name: "Hazbin Hotel Lint"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install Poetry and Project Dependencies
        run: sh .github/scripts/poetry-script.sh

      - name: Install pre-commit and run hooks
        run: sh .github/scripts/pre-commit-script.sh

  test:
    name: "Hazbin Hotel Test"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install Poetry and Project Dependencies
        run: sh .github/scripts/poetry-script.sh

      - name: Run the Tests
        run: poetry run task test --cov-report=xml

      - name: Upload Cov to CodeCov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload html coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-html-coverage
          path: htmlcov/

  # publish-build-docs:

  #   name: "Hazbin Hotel Build Docs and Publish"
  #   runs-on: ${{ matrix.os }}

  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest]

  #   steps:

  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.12.7'

  #     - name: Install Poetry and Project Dependencies
  #       run: sh .github/scripts/poetry-script.sh

  #     - name: Build documentation
  #       run: mkdocs build

  #     - name: Deploy to Read the Docs
  #       env:
  #         READTHEDOCS_API_TOKEN: ${{ secrets.READTHEDOCS_TOKEN }}
  #       run: sh .github/scripts/upload-read-the-docs.sh